Changes in Weatherman branch.
hassaanalii/Weatherman-App pull request #1
Opened 2023-07-31 09:30 UTC by hassaanalii

2023-07-31 10:27 UTC, hussain021 commented on weatherman.py
> +    while temp:
This menu is not required. Please see the document. The program is run through command line using arguments.
e.g: weatherman.py /path/to/files-dir -e 2002

2023-07-31 10:29 UTC, hussain021 commented on weatherman.py
> +    while temp:
The program should be run using "weatherman.py /path/to/files-dir -e 2002" like commands and should print results in the way shown in the document.

2023-07-31 10:30 UTC, hussain021 commented on weatherman.py
> +def module_1(data_list):
Please rename the modules and give explicit and meaningful names.

2023-07-31 10:34 UTC, hussain021 commented
Please update the code to run through command line using arguments and use data structures as well.

2023-08-03 12:10 UTC, hussain021 requested changes

2023-08-03 12:10 UTC, hussain021 commented on yearly_weather_analyzer.py
> +    def __init__(self):
Remove the init function if it is not needed.

2023-08-08 10:32 UTC, hassaanalii commented on monthly_weather_visualizer.py
> +            if day_data['Max TemperatureC'] == '' or day_data['Min TemperatureC'] == '':
It does not have the same effect. One checks if there is an empty string and the other checks if the value is None.

2023-08-08 10:32 UTC, hassaanalii commented on monthly_weather_visualizer.py
> +        for i in range(int(day_data['Max TemperatureC'])):
The implementation is different in both the functions.

2023-08-08 10:34 UTC, hassaanalii commented on weather_data_handler.py
> +        self.months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
Since, there is no need of having a key value pair, having a dictionary would not be appropriate here. I just want the months and loop through them so a list might be the best option here.

2023-08-08 10:35 UTC, hassaanalii commented on yearly_weather_analyzer.py
> +                if max_temp > max_temperature:
Their implementation is almost the same. If I make separate functions, the code will have repetition and increased number of lines.

2023-10-13 06:17 UTC, merged